spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/demodb'
    username: devtest
    password: devtest
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 100
    show-sql: false
  main:
    banner-mode: off
    output:
      ansi.enabled: true
logging:
  level.org.hibernate.SQL: INFO
  level.org.hibernate.type.descriptor.sql.BasicBinder: INFO
  level.de.cmuellerke.kundenverwaltung.configuration.AppConfig: TRACE
  org.hibernate.search.elasticsearch.request: TRACE
  org.hibernate.search.query: TRACE
#  config: classpath:logback.xml
