spring:
  flyway:
    enabled: 'false'
  jpa:
    generate-ddl: 'true'
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        tenant_identifier_resolver: de.cmuellerke.kundenverwaltung.tenancy.TenantIdentifierResolver
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      path: /h2-console
      enabled: 'true'
logging:
  level:
    org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider: DEBUG
    de.cmuellerke: DEBUG
    root: INFO
jwt:
  secret:
    value: javainuseDevTestDevTestDevTest123456789012345678901234567890123456789012345678901234567890
    expiration: '86400000'
